### ISSUE TITLE
Problem with the python essentials cumulative lab

### ISSUE THREAD

**Issue by data-laboratory** [learn-co-curriculum/dsc-python-essentials-lab#8]
When I try to open the json file for the assigment, an error message pops up saying the file does not exist

FileNotFoundError: [Errno 2] No such file or directory: 'coffee_product_reviews.json'

Could you please provide some assistance? Thank you!

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [x] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Let us take a look. Thank you for flagging this.

**Comment by bpurdy-ds** [comment]
You need to download the json file from Canvas, and then place it within the Colab notebook.
As a reminder, this is explained in the **Content Prep: Introduction to Prep** module, and in particular, the _Using Colab_ and _ColabTutorial_ items. If you have further questions, please reach out to your instructor.
